version: '3'

services:
  web:
    container_name: web-ci
    build: .
    command: yarn start
    env_file:
      - .env
    environment:
      - NODE_ENV=ci
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
    depends_on:
      - 'db'
  db:
    container_name: db-ci
    image: mongo:3.6.3
    ports:
      - '27017:27017'
