version: '3'

services:
  web:
    build: .
    command: yarn start
    env_file:
      - .env
    environment:
     - NODE_ENV=integration
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
    depends_on:
      - 'db'
  db:
    image: mongo:latest
    ports:
      - '27019:27017'
    volumes:
      - './db:/data/db'
