version: 2
jobs:
  build:
    working_directory: ~/repo
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Decode dotenv file
          command: echo $ENV_FILE | base64 --decode > .env
      - run:
          name: Install build tools
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
            source ~/.bash_profile
            # cat ~/.bashrc
            nvm install v9.11.1
            nvm use v9.11.1
            npm install -g yarn
      - run:
          name: Check versions
          command: |
            grep -H "" /etc/*version ; grep -H "" /etc/*release
            node --version
            yarn --version
      - run:
          name: Install modules for Client
          command: |
            # if 404 occurred, remove yarn.lock OR yarn upgrade locally before
            #rm client/yarn.lock
            yarn --cwd client install
      - run:
         name: Install modules for Server
         command: yarn install
      - run:
          name: Run docker containers
          command: yarn ci:up
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      #- run:
      #    name: Wait for db
      #    command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - run:
          name: Lint Server
          command: yarn ci:lint
      #- run:
      #    name: Test Server
      #    command: yarn ci:test
      - run:
          name: Build image for production
          command: yarn stage:build
      - run:
          name: Push image to DockerHub for production
          command: yarn stage:push
      - run:
          name: Deploy image to Heroku for staging
          command: yarn stage:deploy
